### ISSUE TITLE
Status error

### ISSUE THREAD

**Issue by Egmara** [JuliaSmoothOptimizers/NLPModelsIpopt.jl#12]
For some problems of `CUTEst`, for example, for the problem named `POWELLSQ`, the output of the function `ipopt.jl` accuses the errors:

```
Error: status infeasible is not a valid status.
ERROR: KeyError: key: infeasible not found.
```

**Comment by abelsiqueira** [comment]
Can you check with the master version of `SolverTools`?

**Comment by Egmara** [comment]
Checked. That worked. Thanks.

**Comment by abelsiqueira** [comment]
I'm registering v0.1.3: https://github.com/JuliaRegistries/General/pull/1192
Thanks for the report.
