### ISSUE TITLE
iter field not updated

### ISSUE THREAD

**Issue by PEPERSO** [JuliaSmoothOptimizers/NLPModelsIpopt.jl#13]
Is it possible to update the iter field in the GenericExecutionStats returned ? 
It is always -1 (default value) in my case...

Thank you !

**Comment by dpo** [comment]
Would you like to try to do it and submit a pull request? https://help.github.com/en/articles/about-pull-requests

**Comment by abelsiqueira** [comment]
I think that the number of iterations is not returned by the `Ipopt.jl` wrapper, but it might be possible to obtain it like the time was obtained, i.e., parsing the output.
